sudo: required

language: bash

services:
  - docker

before_install:
  - docker build -t matteobachetti/mserylak_pulsar_docker . > dockerbuild.log
  - docker run -d -p 127.0.0.1:80:4567 matteobachetti/mserylak_pulsar_docker /bin/sh -c "cd /home/psr"

script:
  - docker ps -a | grep matteobachetti/mserylak_pulsar_docker

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push matteobachetti/mserylak_pulsar_docker;
    fi

after_failure:
  - tail -200 dockerbuild.log